apiVersion: v1
kind: Service
metadata:
  name: tan-dara5304-spring-gradleeeee-service
spec:
  type: NodePort
  selector:
    app: tan-dara5304-spring-gradleeeee
  ports:
    - protocol: TCP
      port: 8323
      targetPort: 8080
